### ISSUE TITLE
Il plugin non si avvia

### ISSUE THREAD

**Issue by goldr31** [ForgottenWorld/FWTownyCustomUpkeep#1]
Versione di Minecraft:
1.15.2

Versione Paper:
Git-Paper-333

Cosa mi aspetto:
avvio del plugin

Cosa accade:

03.06 18:37:40 [Server] ERROR Could not load 'plugins/customupkeep-1.0.0-SNAPSHOT.jar' in folder 'plugins'
03.06 18:37:40 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: it/forgottenworld/customtownyupkeep/CustomTownyUpkeep has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
03.06 18:37:40 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.15.2.jar:git-Paper-333]
03.06 18:37:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-333]
03.06 18:37:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.15.2.jar:git-Paper-333]
03.06 18:37:40 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-333]
03.06 18:37:40 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-333]
03.06 18:37:40 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-333]
03.06 18:37:40 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
03.06 18:37:40 [Server] INFO Caused by: java.lang.UnsupportedClassVersionError: it/forgottenworld/customtownyupkeep/CustomTownyUpkeep has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
03.06 18:37:40 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_242]
03.06 18:37:40 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:757) ~[?:1.8.0_242]
03.06 18:37:40 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_242]
03.06 18:37:40 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.15.2.jar:git-Paper-333]
03.06 18:37:40 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.15.2.jar:git-Paper-333]
03.06 18:37:40 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.15.2.jar:git-Paper-333]
03.06 18:37:40 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-333]
03.06 18:37:40 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
03.06 18:37:40 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
03.06 18:37:40 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
03.06 18:37:40 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
03.06 18:37:40 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.15.2.jar:git-Paper-333]
03.06 18:37:40 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.15.2.jar:git-Paper-333]
03.06 18:37:40 [Server] INFO ... 6 more

**Comment by Filocava99** [comment]
Plugin compilato con una versione troppo recente di Java
