### ISSUE TITLE
Il plugin non prende modifica mantenimento

### ISSUE THREAD

**Issue by goldr31** [ForgottenWorld/FWTownyCustomUpkeep#2]
Versione Minecraft:
1.15.2

Versione Paper:
git-paper-333

Cosa mi aspetto:
venga modificato il mantenimento e allo scattare del nuovo giorno venga prelevato il doppio del mantenimento.

Cosa accade:

allo scattare del nuovo giorno il mantenimento è uguale a quello standard di towny.

Il file config è stato modificato così:

#Towns with custom upkeep
towns-list:
  goldr322: 2
  exampleTown2: 1
#Nations with custom upkeep
Nations-list:
  exampleNation1: 1
  exampleNation2: 1

è stato poi riavviato il server (manca un /reload).

Non viene visualizzato in /t il mantenimento raddoppiato.

Usando /townyadmin newday il mantenimento preso è uguale a quello standard.

**Comment by Filocava99** [comment]
Fixed in 20ec4c432ab3a4b4d42efd3f61fb8a4add0b4f0c
