### ISSUE TITLE
Manca /reload per evitare di riavviare il server

### ISSUE THREAD

**Issue by goldr31** [ForgottenWorld/FWTownyCustomUpkeep#3]
Versione Minecraft:
1.15.2

Versione paper:
git-paper-333

Cosa mi aspetto:
comando /reload per evitare di riavviare il server per prendere i config.

Collegato a #2

**Comment by Filocava99** [comment]
Added in 20ec4c432ab3a4b4d42efd3f61fb8a4add0b4f0c
